- name: Install JDK 8
  apt:
    name: "{{java.VERSION}}"
    state: latest
  bacome: yes
- name: Correct the alternatives to change default Java version.
  alternatives:
    name: java
    link: /bin/java
    path: "{{java.ALTERNATIVES}}"