---
- name: Add java apt repository
  apt_repository:
    repo: "{{ java.repo_URL }}"
    state: present
    update_cache: yes
  become: yes
- name: Install JDK 8
  apt:
    name: "{{ java.VERSION }}"
    state: latest
  become: yes
- name: Correct the alternatives to change default Java version.
  alternatives:
    name: java
    path: "{{ java.ALTERNATIVES }}"
  become: yes